---

- name: Install SNMP
  hosts: all
  become: true
  become_user: root
  vars:
    user:
      login: deploy
      password_hash:
        "$6$NwI7op8FHR1VQta6$zuQXHtNtM/7SRQsf1./18WbBrHMq4mT88nWh67ThmlWcqyVX3F\
        BTY9uj/07tR9ViDEvjg6/bh0y3mSjeDQYe3."
      authorized_key:
        "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr\
        +kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6I\
        edplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2\
        hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZE\
        nDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHln\
        VYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key"
    syslocation: 'Server Room'
    sysadm_contact: 'SysAdmin (devops@example.com)'
  tasks:
    - name: Create admin account
      user:
        name: "{{ user.login }}"
        shell: /bin/bash
        update_password: always
        password: "{{ user.password_hash }}"
    - name: Add admin to sudoers
      lineinfile:
        dest: /etc/sudoers
        state: present
        line: "{{ user.login }} ALL=(ALL:ALL) NOPASSWD:ALL"
    - name: Create authorized key for admin
      authorized_key:
        user: "{{ user.login }}"
        state: present
        key: "{{ user.authorized_key }}"
    - name: Check that user deploy is present in /etc/sudoers
      ansible.builtin.shell:
        cmd: grep deploy /etc/sudoers || echo 'deploy ALL=(ALL:ALL) NOPASSWD:ALL' >> /etc/sudoers
    - name: Install snmpd
      package:
        name:
          - snmpd
        state: present        
    - name: Put snmp.conf in /etc/snmp
      template:
        src: /vagrant/snmpd.conf
        dest: /etc/snmp/snmpd.conf     
    - name: Start snmpd
      systemd:
        name: snmpd
        state: started        
    - name: Allow connections on port 161 (SNMP)
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 161
        ctstate: NEW
        jump: ACCEPT      
    - name: Generate a Self Signed OpenSSL certificate
      openssl_certificate:
        path: /etc/ssl/crt/ansible.com.crt
        privatekey_path: /etc/ssl/private/ansible.com.pem
        csr_path: /etc/ssl/csr/ansible.com.csr
        provider: selfsigned
